# Generated by Django 2.0.10 on 2019-02-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=128, verbose_name='Descrição da Atividade')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('matricula', models.CharField(max_length=12, verbose_name='Matricula')),
                ('função', models.CharField(max_length=128, verbose_name='Função')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.Equipe')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('matricula', models.CharField(max_length=12, verbose_name='Matricula')),
                ('quarto', models.CharField(max_length=128, verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
