# Generated by Django 2.0.10 on 2019-02-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20190214_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ficha', models.CharField(max_length=12, verbose_name='Cód. Ficha')),
                ('motivo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo da Consulta')),
                ('estado_civil', models.CharField(blank=True, choices=[('----', '----'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=15, null=True, verbose_name='Motivo da Consulta')),
                ('profissao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Profissão')),
                ('local', models.CharField(blank=True, choices=[('----', '----'), ('Casa', 'Casa'), ('Trabalho', 'Trabalho'), ('Shopping', 'Shopping'), ('Outros', 'Outros')], max_length=15, null=True, verbose_name='Local das Refeições')),
                ('fumante', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Fumante? ')),
                ('bebida', models.CharField(blank=True, choices=[('----', '----'), ('Nunca', 'Nunca'), ('Socialmente', 'Socialmente'), ('Com frequência', 'Com frequência')], max_length=15, null=True, verbose_name='Faz uso de bebidas alcoólicas')),
                ('diabetes', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Diabetes ')),
                ('colesterol', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Colesterol ')),
                ('anciedade', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Anciedade ')),
                ('infarto', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Infarto ')),
                ('hipertencao', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Hipertenção ')),
                ('cansaco', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Cansaço ')),
                ('gastrite', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Gastrite ')),
                ('dores', models.CharField(blank=True, choices=[('----', '----'), ('Não', 'Não'), ('Sim', 'Sim')], max_length=6, null=True, verbose_name='Dores diárias ')),
                ('diagnostico', models.CharField(blank=True, max_length=300, null=True, verbose_name='Diagnostico Final ')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.Paciente')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
            },
        ),
    ]
