# Generated by Django 2.0.10 on 2019-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_entrevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12, verbose_name='Nome')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='(Q)')),
                ('gramas', models.IntegerField(blank=True, null=True, verbose_name='(g)')),
                ('medida', models.IntegerField(blank=True, null=True, verbose_name='(Medida)')),
                ('proteinas', models.IntegerField(blank=True, null=True, verbose_name='Proteinas')),
                ('carboidrato', models.IntegerField(blank=True, null=True, verbose_name='Carboidrato')),
                ('gordura', models.IntegerField(blank=True, null=True, verbose_name='Gordura')),
                ('calorias', models.IntegerField(blank=True, null=True, verbose_name='Calorias')),
            ],
            options={
                'verbose_name': 'Alimentos',
                'verbose_name_plural': 'Alimentoss',
            },
        ),
    ]
