# Generated by Django 2.0.10 on 2019-02-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_auto_20190215_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='medida',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='(Medida)'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='nome',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
