# Generated by Django 2.0.10 on 2019-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_auto_20190215_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
            },
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('----', '----'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=15, null=True, verbose_name='Estado civil'),
        ),
    ]
