# Generated by Django 2.0.10 on 2019-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0010_auto_20190215_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Preparação de: ')),
            ],
            options={
                'verbose_name': 'Preparo',
                'verbose_name_plural': 'Preparos',
            },
        ),
        migrations.AlterField(
            model_name='refeicoes',
            name='preparo',
            field=models.CharField(max_length=128, verbose_name='Forome'),
        ),
    ]
