# Generated by Django 2.0.10 on 2019-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0011_auto_20190215_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoes',
            name='preparo',
        ),
        migrations.AddField(
            model_name='refeicoes',
            name='preparo',
            field=models.ManyToManyField(to='atendimento.Preparo'),
        ),
    ]
