# Generated by Django 2.0.10 on 2019-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0012_auto_20190215_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='quarto',
            field=models.CharField(choices=[('QT01-Amarelo', 'QT01-Amarelo'), ('QT02-Verde', 'QT02-Verde'), ('QT03-Vermelho', 'QT03-Vermelho'), ('AP01-Amarelo', 'AP01-Amarelo'), ('AP02-Verde', 'AP02-Verde'), ('AP03-Vermelho', 'AP03-Vermelho')], max_length=128, verbose_name='Quarto'),
        ),
    ]
