# Generated by Django 2.0.10 on 2019-02-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0014_auto_20190215_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicoes',
            name='nome',
            field=models.CharField(choices=[('Desjejum', 'Desjejum'), ('Lanche da Manhã', 'Lanche da Manhã'), ('Almoço', 'Almoço'), ('Lanche da Tarde', 'Lanche da Tarde'), ('Jantar', 'Jantar'), ('Lanche da Noite', 'Lanche da Noite')], max_length=128, verbose_name='Refeição'),
        ),
    ]
